services:
  comfyui-worker:
    image: ghcr.io/dariayakovleva/comfyui-runpod:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - SERVE_API_LOCALLY=true
    ports:
      - "8000:8000"
      - "8188:8188"
    volumes:
      - /workspace/models:/comfyui/models 
      - /workspace/output:/comfyui/output 
      - /workspace/custom_nodes:/comfyui/custom_nodes
version: "3.8"
